import ipaddress

from cryptography import x509
from cryptography.x509.oid import NameOID

from backend.tls import _write_self_signed, ensure_data_plane_cert, ensure_self_signed_cert


def _san(cert_path):
    cert = x509.load_pem_x509_certificate(cert_path.read_bytes())
    return cert.extensions.get_extension_for_class(x509.SubjectAlternativeName).value


def _real_pair(tmp_path, name="x", **kw):
    """A genuine self-signed cert/key pair as PEM bytes."""
    c, k = tmp_path / f"{name}.crt", tmp_path / f"{name}.key"
    _write_self_signed(c, k, name, **kw)
    cb, kb = c.read_bytes(), k.read_bytes()
    c.unlink()
    k.unlink()
    return cb, kb


def test_generates_cert_and_key(tmp_path):
    cert = tmp_path / "certs" / "portal.crt"
    key = tmp_path / "certs" / "portal.key"
    ensure_self_signed_cert(cert, key, common_name="pve.example")
    assert cert.exists() and key.exists()

    parsed = x509.load_pem_x509_certificate(cert.read_bytes())
    assert parsed.subject.get_attributes_for_oid(NameOID.COMMON_NAME)[0].value == "pve.example"
    dns = _san(cert).get_values_for_type(x509.DNSName)
    assert "pve.example" in dns and "localhost" in dns


def test_does_not_regenerate_a_valid_pair(tmp_path):
    cert, key = tmp_path / "portal.crt", tmp_path / "portal.key"
    cb, kb = _real_pair(tmp_path, "admin", dns_sans=("portal.example",))
    cert.write_bytes(cb)
    key.write_bytes(kb)
    ensure_self_signed_cert(cert, key, common_name="whatever")
    assert (cert.read_bytes(), key.read_bytes()) == (cb, kb)


def test_refreshes_our_own_torn_pair(tmp_path, caplog):
    cert, key = tmp_path / "portal.crt", tmp_path / "portal.key"
    # Our own auto-generated cert next to a mismatched key (a torn write
    # from a restart loop) -> KEY_VALUES_MISMATCH at uvicorn startup
    # unless we re-issue it here.
    cert.write_bytes(_real_pair(tmp_path, "a")[0])       # has the autogen marker
    key.write_bytes(_real_pair(tmp_path, "b")[1])
    with caplog.at_level("WARNING"):
        ensure_self_signed_cert(cert, key, common_name="pve.example")
    assert any("do not match" in r.message for r in caplog.records)
    parsed = x509.load_pem_x509_certificate(cert.read_bytes())
    assert parsed.subject.get_attributes_for_oid(NameOID.COMMON_NAME)[0].value == "pve.example"


def test_leaves_a_broken_admin_pair_alone(tmp_path, caplog):
    cert, key = tmp_path / "portal.crt", tmp_path / "portal.key"
    cert.write_bytes(b"-----BEGIN CERTIFICATE-----\nnot really\n-----END CERTIFICATE-----\n")
    key.write_bytes(b"not a key either")
    before = (cert.read_bytes(), key.read_bytes())
    with caplog.at_level("ERROR"):
        ensure_self_signed_cert(cert, key, common_name="pve.example")
    assert (cert.read_bytes(), key.read_bytes()) == before  # untouched
    assert any("was not generated by this app" in r.message for r in caplog.records)


# --- data-plane cert (issue #47) ---------------------------------------

def test_data_plane_cert_carries_ip_and_dns_sans(tmp_path):
    cert = tmp_path / "certs" / "data-plane.crt"
    key = tmp_path / "certs" / "data-plane.key"
    ensure_data_plane_cert(cert, key, ip_sans=("10.0.5.5", "10.0.6.5"), dns_sans=("restore.dc1.lan",))
    ips = set(_san(cert).get_values_for_type(x509.IPAddress))
    assert ips == {ipaddress.ip_address("10.0.5.5"), ipaddress.ip_address("10.0.6.5")}
    assert "restore.dc1.lan" in _san(cert).get_values_for_type(x509.DNSName)


def test_data_plane_cert_autogen_regenerates_when_a_nic_ip_changes(tmp_path):
    cert, key = tmp_path / "data-plane.crt", tmp_path / "data-plane.key"
    ensure_data_plane_cert(cert, key, ip_sans=("10.0.5.5",))
    ensure_data_plane_cert(cert, key, ip_sans=("10.0.5.5", "10.0.9.9"))  # NIC added
    ips = {str(v) for v in _san(cert).get_values_for_type(x509.IPAddress)}
    assert ips == {"10.0.5.5", "10.0.9.9"}


def test_data_plane_cert_keeps_an_admin_cert_with_wrong_sans_and_warns(tmp_path, caplog):
    cert, key = tmp_path / "data-plane.crt", tmp_path / "data-plane.key"
    # An admin-supplied pair (no "auto-generated" Organization marker).
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import rsa

    k = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    import datetime

    now = datetime.datetime.now(datetime.UTC)
    subj = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "admin-cert")])
    c = (
        x509.CertificateBuilder()
        .subject_name(subj)
        .issuer_name(subj)
        .public_key(k.public_key())
        .serial_number(1)
        .not_valid_before(now - datetime.timedelta(days=1))
        .not_valid_after(now + datetime.timedelta(days=100))
        .add_extension(x509.SubjectAlternativeName([x509.IPAddress(ipaddress.ip_address("10.0.5.5"))]), False)
        .sign(k, hashes.SHA256())
    )
    cert.write_bytes(c.public_bytes(serialization.Encoding.PEM))
    key.write_bytes(
        k.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.TraditionalOpenSSL,
            serialization.NoEncryption(),
        )
    )
    original = cert.read_bytes()
    with caplog.at_level("WARNING"):
        ensure_data_plane_cert(cert, key, ip_sans=("10.0.5.5", "10.0.9.9"))
    assert cert.read_bytes() == original  # admin's cert untouched
    assert any("does not cover" in r.message for r in caplog.records)


def test_data_plane_cert_reissues_our_own_mismatched_pair(tmp_path, caplog):
    cert, key = tmp_path / "data-plane.crt", tmp_path / "data-plane.key"
    cert.write_bytes(_real_pair(tmp_path, "a", ip_sans=("10.0.5.5",), is_ca=True)[0])
    key.write_bytes(_real_pair(tmp_path, "b", ip_sans=("10.0.5.5",), is_ca=True)[1])
    with caplog.at_level("WARNING"):
        ensure_data_plane_cert(cert, key, ip_sans=("10.0.5.5",))
    assert any("do not match" in r.message for r in caplog.records)
    from backend.tls import _pair_broken_reason

    assert _pair_broken_reason(cert, key) is None  # fixed


def test_data_plane_cert_leaves_a_broken_admin_pair_alone(tmp_path, caplog):
    cert, key = tmp_path / "data-plane.crt", tmp_path / "data-plane.key"
    cert.write_bytes(b"junk cert")
    key.write_bytes(b"junk key")
    before = (cert.read_bytes(), key.read_bytes())
    with caplog.at_level("ERROR"):
        ensure_data_plane_cert(cert, key, ip_sans=("10.0.5.5",))
    assert (cert.read_bytes(), key.read_bytes()) == before
    assert any("was not generated by this app" in r.message for r in caplog.records)
